name: Update Buniadpur CAPEX JSON

on:
  schedule:
    - cron: '30 8 * * *'  # Every day at 2:00 PM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Fetch and Convert Buniadpur CSVs
        run: |
          mkdir -p data

          # Download and convert CAPEX CSV
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTZPn6CB_cHTFVb8S5vpvaBnczj63fYMTI0RVEdMzVcQ8O6XQi5iwTbMp2xa5vsL6zHGWxezWUSehrN/pub?gid=1865929221&single=true&output=csv" -o data/bbdp_capex.csv
          csvtojson data/bbdp_capex.csv > data/bbdp_capex.json

          # Download and convert Vendor CSV
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTZPn6CB_cHTFVb8S5vpvaBnczj63fYMTI0RVEdMzVcQ8O6XQi5iwTbMp2xa5vsL6zHGWxezWUSehrN/pub?gid=1818971964&single=true&output=csv" -o data/bndp_vendor.csv
          csvtojson data/bndp_vendor.csv > data/bndp_vendor.json

      - name: Commit and Push JSON Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/bbdp_capex.json data/bndp_vendor.json || true
          git diff --cached --quiet && echo "✅ No changes to commit." || (git commit -m "Update Buniadpur JSON data" && git push)
