name: Update Capex All JSON

on:
  schedule:
    - cron: '30 8 * * *'  # Every day at 2:00 PM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Fetch and Convert Capex All CSV
        run: |
          mkdir -p data
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQI2neSVbvMR4fF910Q0AWUcq02leP-sob8q4f9goT46hgLutCpxCjSL6y6X3s2vYBJRNN7WrFCjE0R/pub?gid=439685010&single=true&output=csv" -o data/capexall.csv
          csvtojson data/capexall.csv > data/capexall.json

      - name: Commit and Push JSON File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/capexall.json || true
          git diff --cached --quiet && echo "✅ No changes to commit." || (git commit -m "Update Capex All JSON data" && git push)
