name: Update Advance Division JSONs

on:
  schedule:
    - cron: '30 5 * * *'  # 11 AM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install -g csvtojson

      - name: Fetch and convert each division sheet
        run: |
          mkdir -p data
          declare -A urls
          urls[advance-balurghat]="https://docs.google.com/spreadsheets/d/e/2PACX-1vRooKVx76f92WX_Q3j2u4UmA1yXN2cNcwSPVqiFjyY58oTplAg_Ieze4xket4Lq3qHEuLt9js0-kU8a/pub?output=csv"
          urls[advance-malda]="https://docs.google.com/spreadsheets/d/e/2PACX-1vQHtBkI-9-cafLDNyCNtbnHX0B65dCawQHoO8oiFYQzeWBxu0u4VBXCqR5zgj5ylceF3piSl8rnholp/pub?output=csv"
          urls[advance-raiganj]="https://docs.google.com/spreadsheets/d/e/2PACX-1vR-jd3bm9BCgUKNQCgr0Lj9paLYQ9oacLPlleCHXrtV1__58NyK_w19hbC4thzgPkdHtIAAP2nrnmyC/pub?output=csv"
          urls[advance-buniadpur]="https://docs.google.com/spreadsheets/d/e/2PACX-1vT7Q8EgbBzDoLIGRZh-5dPUmJUIXtfzlsz64AKKLXUowEfnq-Ke7MNW_XWd8UsyAKqOT4nxJ0m_czzc/pub?output=csv"
          urls[advance-gazole]="https://docs.google.com/spreadsheets/d/e/2PACX-1vQekKrHhSpV7p6yaYVSA4UXTO6DYws9eZBhD0JTXoWxog7L9eLDkFyxtb3ohtJOGTC-XEwhT2s0x4Aj/pub?output=csv"
          urls[advance-islampur]="https://docs.google.com/spreadsheets/d/e/2PACX-1vRY_EzVWtDZxQlvktlWsTbvHpK_lIPMuDABdV_-xqbGOGEvR4ZJrJrRaEjWZIG70sB8gg_HbLTpxaC2/pub?output=csv"
          urls[advance-chanchal]="https://docs.google.com/spreadsheets/d/e/2PACX-1vQzN7wwuCEyA9bH6sdBoW3dIxCK9Dvh5bS0vWyRM57YXLH9iMIxLIXGyWqffE1xFtPCk2sZXtcDbtlC/pub?output=csv"

          for key in "${!urls[@]}"; do
            echo "Fetching ${key}.csv"
            curl -L "${urls[$key]}" -o "data/${key}.csv"
            csvtojson "data/${key}.csv" > "data/${key}.json"
          done

      - name: Commit and Push JSONs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/*.json || true
          git diff --cached --quiet || git commit -m "Update advance division JSONs" && git push
