name: Update NSC JSON

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 11 AM IST
  workflow_dispatch:

jobs:
  update-nsc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Fetch and Convert NSC Sheet to JSON
        run: |
          mkdir -p data
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRsUU2viBvYhSgR0RFwmZ1H8LkYCats9roQVCKvQeoU7dzg6ryR6IWZex9FT9tksp_DEM23ZgQ28Iyo/pub?output=csv" -o data/nsc.csv
          csvtojson data/nsc.csv > data/nsc.json

      - name: Commit and Push JSON (only if changed)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/nsc.json || true
          git diff --cached --quiet && echo "✅ No changes to commit." || (git commit -m "Auto-update nsc.json" && git push)

