name: Update Advance Division JSONs

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 11 AM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Fetch and Convert Division Sheets
        run: |
          mkdir -p data

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRooKVx76f92WX_Q3j2u4UmA1yXN2cNcwSPVqiFjyY58oTplAg_Ieze4xket4Lq3qHEuLt9js0-kU8a/pub?output=csv" -o data/advance-balurghat.csv
          csvtojson data/advance-balurghat.csv > data/advance-balurghat.json

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQHtBkI-9-cafLDNyCNtbnHX0B65dCawQHoO8oiFYQzeWBxu0u4VBXCqR5zgj5ylceF3piSl8rnholp/pub?output=csv" -o data/advance-malda.csv
          csvtojson data/advance-malda.csv > data/advance-malda.json

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vR-jd3bm9BCgUKNQCgr0Lj9paLYQ9oacLPlleCHXrtV1__58NyK_w19hbC4thzgPkdHtIAAP2nrnmyC/pub?output=csv" -o data/advance-raiganj.csv
          csvtojson data/advance-raiganj.csv > data/advance-raiganj.json

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vT7Q8EgbBzDoLIGRZh-5dPUmJUIXtfzlsz64AKKLXUowEfnq-Ke7MNW_XWd8UsyAKqOT4nxJ0m_czzc/pub?output=csv" -o data/advance-buniadpur.csv
          csvtojson data/advance-buniadpur.csv > data/advance-buniadpur.json

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQekKrHhSpV7p6yaYVSA4UXTO6DYws9eZBhD0JTXoWxog7L9eLDkFyxtb3ohtJOGTC-XEwhT2s0x4Aj/pub?output=csv" -o data/advance-gazole.csv
          csvtojson data/advance-gazole.csv > data/advance-gazole.json

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRY_EzVWtDZxQlvktlWsTbvHpK_lIPMuDABdV_-xqbGOGEvR4ZJrJrRaEjWZIG70sB8gg_HbLTpxaC2/pub?output=csv" -o data/advance-islampur.csv
          csvtojson data/advance-islampur.csv > data/advance-islampur.json

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vQzN7wwuCEyA9bH6sdBoW3dIxCK9Dvh5bS0vWyRM57YXLH9iMIxLIXGyWqffE1xFtPCk2sZXtcDbtlC/pub?output=csv" -o data/advance-chanchal.csv
          csvtojson data/advance-chanchal.csv > data/advance-chanchal.json

      - name: Commit and Push JSONs (only if changed)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/advance-*.json || true
          git diff --cached --quiet && echo "✅ No changes to commit." || (git commit -m "Auto-update advance division JSONs" && git push)
