name: Daily JSON Update

on:
  schedule:
    - cron: '30 8 * * *'  # 2 PM IST = 8:30 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install papaparse node-fetch

      - name: Convert Google Sheet CSV to JSON
        run: node scripts/fetch_and_convert.js

      - name: Commit and Push JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add data/*.json
          git commit -m "Update JSON data @ $(date -u)" || echo "No changes"
          git push
