name: Update REM JSON

on:
  schedule:
    - cron: '30 5 * * *'  # Every day at 11:00 AM IST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install csvtojson
        run: npm install -g csvtojson

      - name: Fetch and Convert REM Sheet
        run: |
          mkdir -p data

          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vT_CmsyvD833bjicZVVhRGXWNPrwb_WqpgYkfeVlcmD0hsm0gwSQHsofNo2JPjedUBdpMPGxK7B4Rqy/pub?output=csv" -o data/rem.csv
          csvtojson data/rem.csv > data/rem.json

      - name: Commit and Push REM JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/rem.json || true
          git diff --cached --quiet && echo "✅ No changes to commit." || (git commit -m "Update REM JSON data" && git push)
